/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppShipmentsImport } from './routes/app/shipments'
import { Route as AppClientsClientIdInvoicesIndexImport } from './routes/app/clients/$clientId/invoices/index'
import { Route as AppClientsClientIdInvoicesInvoiceIdIndexImport } from './routes/app/clients/$clientId/invoices/$invoiceId/index'
import { Route as AppClientsClientIdInvoicesInvoiceIdPdfImport } from './routes/app/clients/$clientId/invoices/$invoiceId/pdf'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppShipmentsRoute = AppShipmentsImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppClientsClientIdInvoicesIndexRoute =
  AppClientsClientIdInvoicesIndexImport.update({
    id: '/clients/$clientId/invoices/',
    path: '/clients/$clientId/invoices/',
    getParentRoute: () => AppRouteRoute,
  } as any)

const AppClientsClientIdInvoicesInvoiceIdIndexRoute =
  AppClientsClientIdInvoicesInvoiceIdIndexImport.update({
    id: '/clients/$clientId/invoices/$invoiceId/',
    path: '/clients/$clientId/invoices/$invoiceId/',
    getParentRoute: () => AppRouteRoute,
  } as any)

const AppClientsClientIdInvoicesInvoiceIdPdfRoute =
  AppClientsClientIdInvoicesInvoiceIdPdfImport.update({
    id: '/clients/$clientId/invoices/$invoiceId/pdf',
    path: '/clients/$clientId/invoices/$invoiceId/pdf',
    getParentRoute: () => AppRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/app/shipments': {
      id: '/app/shipments'
      path: '/shipments'
      fullPath: '/app/shipments'
      preLoaderRoute: typeof AppShipmentsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/clients/$clientId/invoices/': {
      id: '/app/clients/$clientId/invoices/'
      path: '/clients/$clientId/invoices'
      fullPath: '/app/clients/$clientId/invoices'
      preLoaderRoute: typeof AppClientsClientIdInvoicesIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/clients/$clientId/invoices/$invoiceId/pdf': {
      id: '/app/clients/$clientId/invoices/$invoiceId/pdf'
      path: '/clients/$clientId/invoices/$invoiceId/pdf'
      fullPath: '/app/clients/$clientId/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof AppClientsClientIdInvoicesInvoiceIdPdfImport
      parentRoute: typeof AppRouteImport
    }
    '/app/clients/$clientId/invoices/$invoiceId/': {
      id: '/app/clients/$clientId/invoices/$invoiceId/'
      path: '/clients/$clientId/invoices/$invoiceId'
      fullPath: '/app/clients/$clientId/invoices/$invoiceId'
      preLoaderRoute: typeof AppClientsClientIdInvoicesInvoiceIdIndexImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppShipmentsRoute: typeof AppShipmentsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdInvoicesIndexRoute: typeof AppClientsClientIdInvoicesIndexRoute
  AppClientsClientIdInvoicesInvoiceIdPdfRoute: typeof AppClientsClientIdInvoicesInvoiceIdPdfRoute
  AppClientsClientIdInvoicesInvoiceIdIndexRoute: typeof AppClientsClientIdInvoicesInvoiceIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppShipmentsRoute: AppShipmentsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdInvoicesIndexRoute: AppClientsClientIdInvoicesIndexRoute,
  AppClientsClientIdInvoicesInvoiceIdPdfRoute:
    AppClientsClientIdInvoicesInvoiceIdPdfRoute,
  AppClientsClientIdInvoicesInvoiceIdIndexRoute:
    AppClientsClientIdInvoicesInvoiceIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId/invoices': typeof AppClientsClientIdInvoicesIndexRoute
  '/app/clients/$clientId/invoices/$invoiceId/pdf': typeof AppClientsClientIdInvoicesInvoiceIdPdfRoute
  '/app/clients/$clientId/invoices/$invoiceId': typeof AppClientsClientIdInvoicesInvoiceIdIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$clientId/invoices': typeof AppClientsClientIdInvoicesIndexRoute
  '/app/clients/$clientId/invoices/$invoiceId/pdf': typeof AppClientsClientIdInvoicesInvoiceIdPdfRoute
  '/app/clients/$clientId/invoices/$invoiceId': typeof AppClientsClientIdInvoicesInvoiceIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId/invoices/': typeof AppClientsClientIdInvoicesIndexRoute
  '/app/clients/$clientId/invoices/$invoiceId/pdf': typeof AppClientsClientIdInvoicesInvoiceIdPdfRoute
  '/app/clients/$clientId/invoices/$invoiceId/': typeof AppClientsClientIdInvoicesInvoiceIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/app/shipments'
    | '/app/'
    | '/app/clients/$clientId/invoices'
    | '/app/clients/$clientId/invoices/$invoiceId/pdf'
    | '/app/clients/$clientId/invoices/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/app/shipments'
    | '/app'
    | '/app/clients/$clientId/invoices'
    | '/app/clients/$clientId/invoices/$invoiceId/pdf'
    | '/app/clients/$clientId/invoices/$invoiceId'
  id:
    | '__root__'
    | '/app'
    | '/login'
    | '/app/shipments'
    | '/app/'
    | '/app/clients/$clientId/invoices/'
    | '/app/clients/$clientId/invoices/$invoiceId/pdf'
    | '/app/clients/$clientId/invoices/$invoiceId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/app",
        "/login"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/shipments",
        "/app/",
        "/app/clients/$clientId/invoices/",
        "/app/clients/$clientId/invoices/$invoiceId/pdf",
        "/app/clients/$clientId/invoices/$invoiceId/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/app/shipments": {
      "filePath": "app/shipments.tsx",
      "parent": "/app"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/clients/$clientId/invoices/": {
      "filePath": "app/clients/$clientId/invoices/index.tsx",
      "parent": "/app"
    },
    "/app/clients/$clientId/invoices/$invoiceId/pdf": {
      "filePath": "app/clients/$clientId/invoices/$invoiceId/pdf.tsx",
      "parent": "/app"
    },
    "/app/clients/$clientId/invoices/$invoiceId/": {
      "filePath": "app/clients/$clientId/invoices/$invoiceId/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
